//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gswsBackendAPI.HousesiteWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="APISoap", Namespace="http://tempuri.org/")]
    public partial class API : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GVS_CITIZENSERVICESCOUNTOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback HouseSitePattaApplication_AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback HouseSitePattaApplication_Add2OperationCompleted;
        
        private System.Threading.SendOrPostCallback HouseSitePattaApplication_StatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHSP_APP_StatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHSP_APP_ByDate_StatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPopulateVillagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPopulateSurveyNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPopulateKhataNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertLandCoordinatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_LandCoordinatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPopulateVillages_NewOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertLCDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLandGeoCoordinatesDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLandGeoCoordinatesDetails_newOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETAPPSTATUSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETDATEWISEAPPROVEDLISTOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTokenSSOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public API() {
            this.Url = global::gswsBackendAPI.Properties.Settings.Default.gswsBackendAPI_HousesiteWebservice_API;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GVS_CITIZENSERVICESCOUNTCompletedEventHandler GVS_CITIZENSERVICESCOUNTCompleted;
        
        /// <remarks/>
        public event GetTokenCompletedEventHandler GetTokenCompleted;
        
        /// <remarks/>
        public event HouseSitePattaApplication_AddCompletedEventHandler HouseSitePattaApplication_AddCompleted;
        
        /// <remarks/>
        public event HouseSitePattaApplication_Add2CompletedEventHandler HouseSitePattaApplication_Add2Completed;
        
        /// <remarks/>
        public event HouseSitePattaApplication_StatusCompletedEventHandler HouseSitePattaApplication_StatusCompleted;
        
        /// <remarks/>
        public event GetHSP_APP_StatusCompletedEventHandler GetHSP_APP_StatusCompleted;
        
        /// <remarks/>
        public event GetHSP_APP_ByDate_StatusCompletedEventHandler GetHSP_APP_ByDate_StatusCompleted;
        
        /// <remarks/>
        public event GetPopulateVillagesCompletedEventHandler GetPopulateVillagesCompleted;
        
        /// <remarks/>
        public event GetPopulateSurveyNumbersCompletedEventHandler GetPopulateSurveyNumbersCompleted;
        
        /// <remarks/>
        public event GetPopulateKhataNumbersCompletedEventHandler GetPopulateKhataNumbersCompleted;
        
        /// <remarks/>
        public event InsertLandCoordinatesCompletedEventHandler InsertLandCoordinatesCompleted;
        
        /// <remarks/>
        public event Get_LandCoordinatesCompletedEventHandler Get_LandCoordinatesCompleted;
        
        /// <remarks/>
        public event GetPopulateVillages_NewCompletedEventHandler GetPopulateVillages_NewCompleted;
        
        /// <remarks/>
        public event InsertLCDataCompletedEventHandler InsertLCDataCompleted;
        
        /// <remarks/>
        public event GetLandGeoCoordinatesDetailsCompletedEventHandler GetLandGeoCoordinatesDetailsCompleted;
        
        /// <remarks/>
        public event GetLandGeoCoordinatesDetails_newCompletedEventHandler GetLandGeoCoordinatesDetails_newCompleted;
        
        /// <remarks/>
        public event getPDFCompletedEventHandler getPDFCompleted;
        
        /// <remarks/>
        public event GETAPPSTATUSCompletedEventHandler GETAPPSTATUSCompleted;
        
        /// <remarks/>
        public event GETDATEWISEAPPROVEDLISTCompletedEventHandler GETDATEWISEAPPROVEDLISTCompleted;
        
        /// <remarks/>
        public event GetTokenSSOCompletedEventHandler GetTokenSSOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GVS_CITIZENSERVICESCOUNT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GVS_CITIZENSERVICESCOUNT(System.DateTime FromDate, System.DateTime ToDate, string userid, string password) {
            object[] results = this.Invoke("GVS_CITIZENSERVICESCOUNT", new object[] {
                        FromDate,
                        ToDate,
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GVS_CITIZENSERVICESCOUNTAsync(System.DateTime FromDate, System.DateTime ToDate, string userid, string password) {
            this.GVS_CITIZENSERVICESCOUNTAsync(FromDate, ToDate, userid, password, null);
        }
        
        /// <remarks/>
        public void GVS_CITIZENSERVICESCOUNTAsync(System.DateTime FromDate, System.DateTime ToDate, string userid, string password, object userState) {
            if ((this.GVS_CITIZENSERVICESCOUNTOperationCompleted == null)) {
                this.GVS_CITIZENSERVICESCOUNTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGVS_CITIZENSERVICESCOUNTOperationCompleted);
            }
            this.InvokeAsync("GVS_CITIZENSERVICESCOUNT", new object[] {
                        FromDate,
                        ToDate,
                        userid,
                        password}, this.GVS_CITIZENSERVICESCOUNTOperationCompleted, userState);
        }
        
        private void OnGVS_CITIZENSERVICESCOUNTOperationCompleted(object arg) {
            if ((this.GVS_CITIZENSERVICESCOUNTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GVS_CITIZENSERVICESCOUNTCompleted(this, new GVS_CITIZENSERVICESCOUNTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetToken(string userid, string password) {
            object[] results = this.Invoke("GetToken", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTokenAsync(string userid, string password) {
            this.GetTokenAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void GetTokenAsync(string userid, string password, object userState) {
            if ((this.GetTokenOperationCompleted == null)) {
                this.GetTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTokenOperationCompleted);
            }
            this.InvokeAsync("GetToken", new object[] {
                        userid,
                        password}, this.GetTokenOperationCompleted, userState);
        }
        
        private void OnGetTokenOperationCompleted(object arg) {
            if ((this.GetTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTokenCompleted(this, new GetTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HouseSitePattaApplication_Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HouseSitePattaApplication_Add(string userid, string password, string token, HousePattaBO HouseBO) {
            object[] results = this.Invoke("HouseSitePattaApplication_Add", new object[] {
                        userid,
                        password,
                        token,
                        HouseBO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HouseSitePattaApplication_AddAsync(string userid, string password, string token, HousePattaBO HouseBO) {
            this.HouseSitePattaApplication_AddAsync(userid, password, token, HouseBO, null);
        }
        
        /// <remarks/>
        public void HouseSitePattaApplication_AddAsync(string userid, string password, string token, HousePattaBO HouseBO, object userState) {
            if ((this.HouseSitePattaApplication_AddOperationCompleted == null)) {
                this.HouseSitePattaApplication_AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHouseSitePattaApplication_AddOperationCompleted);
            }
            this.InvokeAsync("HouseSitePattaApplication_Add", new object[] {
                        userid,
                        password,
                        token,
                        HouseBO}, this.HouseSitePattaApplication_AddOperationCompleted, userState);
        }
        
        private void OnHouseSitePattaApplication_AddOperationCompleted(object arg) {
            if ((this.HouseSitePattaApplication_AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HouseSitePattaApplication_AddCompleted(this, new HouseSitePattaApplication_AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HouseSitePattaApplication_Add2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HouseSitePattaApplication_Add2(string userid, string password, string token, string HouseBO2) {
            object[] results = this.Invoke("HouseSitePattaApplication_Add2", new object[] {
                        userid,
                        password,
                        token,
                        HouseBO2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HouseSitePattaApplication_Add2Async(string userid, string password, string token, string HouseBO2) {
            this.HouseSitePattaApplication_Add2Async(userid, password, token, HouseBO2, null);
        }
        
        /// <remarks/>
        public void HouseSitePattaApplication_Add2Async(string userid, string password, string token, string HouseBO2, object userState) {
            if ((this.HouseSitePattaApplication_Add2OperationCompleted == null)) {
                this.HouseSitePattaApplication_Add2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHouseSitePattaApplication_Add2OperationCompleted);
            }
            this.InvokeAsync("HouseSitePattaApplication_Add2", new object[] {
                        userid,
                        password,
                        token,
                        HouseBO2}, this.HouseSitePattaApplication_Add2OperationCompleted, userState);
        }
        
        private void OnHouseSitePattaApplication_Add2OperationCompleted(object arg) {
            if ((this.HouseSitePattaApplication_Add2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HouseSitePattaApplication_Add2Completed(this, new HouseSitePattaApplication_Add2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HouseSitePattaApplication_Status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HouseSitePattaApplication_Status(string userid, string password, string token, string APPNO) {
            object[] results = this.Invoke("HouseSitePattaApplication_Status", new object[] {
                        userid,
                        password,
                        token,
                        APPNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HouseSitePattaApplication_StatusAsync(string userid, string password, string token, string APPNO) {
            this.HouseSitePattaApplication_StatusAsync(userid, password, token, APPNO, null);
        }
        
        /// <remarks/>
        public void HouseSitePattaApplication_StatusAsync(string userid, string password, string token, string APPNO, object userState) {
            if ((this.HouseSitePattaApplication_StatusOperationCompleted == null)) {
                this.HouseSitePattaApplication_StatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHouseSitePattaApplication_StatusOperationCompleted);
            }
            this.InvokeAsync("HouseSitePattaApplication_Status", new object[] {
                        userid,
                        password,
                        token,
                        APPNO}, this.HouseSitePattaApplication_StatusOperationCompleted, userState);
        }
        
        private void OnHouseSitePattaApplication_StatusOperationCompleted(object arg) {
            if ((this.HouseSitePattaApplication_StatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HouseSitePattaApplication_StatusCompleted(this, new HouseSitePattaApplication_StatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHSP_APP_Status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHSP_APP_Status(string userid, string password, string token, string APPNO) {
            object[] results = this.Invoke("GetHSP_APP_Status", new object[] {
                        userid,
                        password,
                        token,
                        APPNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHSP_APP_StatusAsync(string userid, string password, string token, string APPNO) {
            this.GetHSP_APP_StatusAsync(userid, password, token, APPNO, null);
        }
        
        /// <remarks/>
        public void GetHSP_APP_StatusAsync(string userid, string password, string token, string APPNO, object userState) {
            if ((this.GetHSP_APP_StatusOperationCompleted == null)) {
                this.GetHSP_APP_StatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHSP_APP_StatusOperationCompleted);
            }
            this.InvokeAsync("GetHSP_APP_Status", new object[] {
                        userid,
                        password,
                        token,
                        APPNO}, this.GetHSP_APP_StatusOperationCompleted, userState);
        }
        
        private void OnGetHSP_APP_StatusOperationCompleted(object arg) {
            if ((this.GetHSP_APP_StatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHSP_APP_StatusCompleted(this, new GetHSP_APP_StatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHSP_APP_ByDate_Status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHSP_APP_ByDate_Status(string userid, string password, string token, string FromDate, string ToDate) {
            object[] results = this.Invoke("GetHSP_APP_ByDate_Status", new object[] {
                        userid,
                        password,
                        token,
                        FromDate,
                        ToDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHSP_APP_ByDate_StatusAsync(string userid, string password, string token, string FromDate, string ToDate) {
            this.GetHSP_APP_ByDate_StatusAsync(userid, password, token, FromDate, ToDate, null);
        }
        
        /// <remarks/>
        public void GetHSP_APP_ByDate_StatusAsync(string userid, string password, string token, string FromDate, string ToDate, object userState) {
            if ((this.GetHSP_APP_ByDate_StatusOperationCompleted == null)) {
                this.GetHSP_APP_ByDate_StatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHSP_APP_ByDate_StatusOperationCompleted);
            }
            this.InvokeAsync("GetHSP_APP_ByDate_Status", new object[] {
                        userid,
                        password,
                        token,
                        FromDate,
                        ToDate}, this.GetHSP_APP_ByDate_StatusOperationCompleted, userState);
        }
        
        private void OnGetHSP_APP_ByDate_StatusOperationCompleted(object arg) {
            if ((this.GetHSP_APP_ByDate_StatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHSP_APP_ByDate_StatusCompleted(this, new GetHSP_APP_ByDate_StatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPopulateVillages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPopulateVillages(string userid, string password, string version) {
            object[] results = this.Invoke("GetPopulateVillages", new object[] {
                        userid,
                        password,
                        version});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPopulateVillagesAsync(string userid, string password, string version) {
            this.GetPopulateVillagesAsync(userid, password, version, null);
        }
        
        /// <remarks/>
        public void GetPopulateVillagesAsync(string userid, string password, string version, object userState) {
            if ((this.GetPopulateVillagesOperationCompleted == null)) {
                this.GetPopulateVillagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPopulateVillagesOperationCompleted);
            }
            this.InvokeAsync("GetPopulateVillages", new object[] {
                        userid,
                        password,
                        version}, this.GetPopulateVillagesOperationCompleted, userState);
        }
        
        private void OnGetPopulateVillagesOperationCompleted(object arg) {
            if ((this.GetPopulateVillagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPopulateVillagesCompleted(this, new GetPopulateVillagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPopulateSurveyNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPopulateSurveyNumbers(string userid, string password, string MandalId, string villageId) {
            object[] results = this.Invoke("GetPopulateSurveyNumbers", new object[] {
                        userid,
                        password,
                        MandalId,
                        villageId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPopulateSurveyNumbersAsync(string userid, string password, string MandalId, string villageId) {
            this.GetPopulateSurveyNumbersAsync(userid, password, MandalId, villageId, null);
        }
        
        /// <remarks/>
        public void GetPopulateSurveyNumbersAsync(string userid, string password, string MandalId, string villageId, object userState) {
            if ((this.GetPopulateSurveyNumbersOperationCompleted == null)) {
                this.GetPopulateSurveyNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPopulateSurveyNumbersOperationCompleted);
            }
            this.InvokeAsync("GetPopulateSurveyNumbers", new object[] {
                        userid,
                        password,
                        MandalId,
                        villageId}, this.GetPopulateSurveyNumbersOperationCompleted, userState);
        }
        
        private void OnGetPopulateSurveyNumbersOperationCompleted(object arg) {
            if ((this.GetPopulateSurveyNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPopulateSurveyNumbersCompleted(this, new GetPopulateSurveyNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPopulateKhataNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPopulateKhataNumbers(string userid, string password, string MandalId, string villageId, string SurveyNo) {
            object[] results = this.Invoke("GetPopulateKhataNumbers", new object[] {
                        userid,
                        password,
                        MandalId,
                        villageId,
                        SurveyNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPopulateKhataNumbersAsync(string userid, string password, string MandalId, string villageId, string SurveyNo) {
            this.GetPopulateKhataNumbersAsync(userid, password, MandalId, villageId, SurveyNo, null);
        }
        
        /// <remarks/>
        public void GetPopulateKhataNumbersAsync(string userid, string password, string MandalId, string villageId, string SurveyNo, object userState) {
            if ((this.GetPopulateKhataNumbersOperationCompleted == null)) {
                this.GetPopulateKhataNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPopulateKhataNumbersOperationCompleted);
            }
            this.InvokeAsync("GetPopulateKhataNumbers", new object[] {
                        userid,
                        password,
                        MandalId,
                        villageId,
                        SurveyNo}, this.GetPopulateKhataNumbersOperationCompleted, userState);
        }
        
        private void OnGetPopulateKhataNumbersOperationCompleted(object arg) {
            if ((this.GetPopulateKhataNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPopulateKhataNumbersCompleted(this, new GetPopulateKhataNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertLandCoordinates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertLandCoordinates(
                    string userid, 
                    string password, 
                    int DistrictCode, 
                    int MandalCode, 
                    int VillageCode, 
                    string SurveyNo, 
                    string KhathaNo, 
                    string Extent, 
                    string CRD1, 
                    string CRD2, 
                    string CRD3, 
                    string CRD4, 
                    string CRD5, 
                    string CRD6, 
                    string CRD7, 
                    string CRD8, 
                    string CRD9, 
                    string CRD10, 
                    string UTM1, 
                    string UTM2, 
                    string UTM3, 
                    string UTM4, 
                    string UTM5, 
                    string UTM6, 
                    string UTM7, 
                    string UTM8, 
                    string UTM9, 
                    string UTM10, 
                    string Remarks1, 
                    string Remarks2, 
                    string Remarks3, 
                    string Remarks4, 
                    string Remarks5, 
                    string Remarks6, 
                    string Remarks7, 
                    string Remarks8, 
                    string Remarks9, 
                    string Remarks10, 
                    string CreatedBy, 
                    string IPAddress, 
                    string GeoCoordinateImage) {
            object[] results = this.Invoke("InsertLandCoordinates", new object[] {
                        userid,
                        password,
                        DistrictCode,
                        MandalCode,
                        VillageCode,
                        SurveyNo,
                        KhathaNo,
                        Extent,
                        CRD1,
                        CRD2,
                        CRD3,
                        CRD4,
                        CRD5,
                        CRD6,
                        CRD7,
                        CRD8,
                        CRD9,
                        CRD10,
                        UTM1,
                        UTM2,
                        UTM3,
                        UTM4,
                        UTM5,
                        UTM6,
                        UTM7,
                        UTM8,
                        UTM9,
                        UTM10,
                        Remarks1,
                        Remarks2,
                        Remarks3,
                        Remarks4,
                        Remarks5,
                        Remarks6,
                        Remarks7,
                        Remarks8,
                        Remarks9,
                        Remarks10,
                        CreatedBy,
                        IPAddress,
                        GeoCoordinateImage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertLandCoordinatesAsync(
                    string userid, 
                    string password, 
                    int DistrictCode, 
                    int MandalCode, 
                    int VillageCode, 
                    string SurveyNo, 
                    string KhathaNo, 
                    string Extent, 
                    string CRD1, 
                    string CRD2, 
                    string CRD3, 
                    string CRD4, 
                    string CRD5, 
                    string CRD6, 
                    string CRD7, 
                    string CRD8, 
                    string CRD9, 
                    string CRD10, 
                    string UTM1, 
                    string UTM2, 
                    string UTM3, 
                    string UTM4, 
                    string UTM5, 
                    string UTM6, 
                    string UTM7, 
                    string UTM8, 
                    string UTM9, 
                    string UTM10, 
                    string Remarks1, 
                    string Remarks2, 
                    string Remarks3, 
                    string Remarks4, 
                    string Remarks5, 
                    string Remarks6, 
                    string Remarks7, 
                    string Remarks8, 
                    string Remarks9, 
                    string Remarks10, 
                    string CreatedBy, 
                    string IPAddress, 
                    string GeoCoordinateImage) {
            this.InsertLandCoordinatesAsync(userid, password, DistrictCode, MandalCode, VillageCode, SurveyNo, KhathaNo, Extent, CRD1, CRD2, CRD3, CRD4, CRD5, CRD6, CRD7, CRD8, CRD9, CRD10, UTM1, UTM2, UTM3, UTM4, UTM5, UTM6, UTM7, UTM8, UTM9, UTM10, Remarks1, Remarks2, Remarks3, Remarks4, Remarks5, Remarks6, Remarks7, Remarks8, Remarks9, Remarks10, CreatedBy, IPAddress, GeoCoordinateImage, null);
        }
        
        /// <remarks/>
        public void InsertLandCoordinatesAsync(
                    string userid, 
                    string password, 
                    int DistrictCode, 
                    int MandalCode, 
                    int VillageCode, 
                    string SurveyNo, 
                    string KhathaNo, 
                    string Extent, 
                    string CRD1, 
                    string CRD2, 
                    string CRD3, 
                    string CRD4, 
                    string CRD5, 
                    string CRD6, 
                    string CRD7, 
                    string CRD8, 
                    string CRD9, 
                    string CRD10, 
                    string UTM1, 
                    string UTM2, 
                    string UTM3, 
                    string UTM4, 
                    string UTM5, 
                    string UTM6, 
                    string UTM7, 
                    string UTM8, 
                    string UTM9, 
                    string UTM10, 
                    string Remarks1, 
                    string Remarks2, 
                    string Remarks3, 
                    string Remarks4, 
                    string Remarks5, 
                    string Remarks6, 
                    string Remarks7, 
                    string Remarks8, 
                    string Remarks9, 
                    string Remarks10, 
                    string CreatedBy, 
                    string IPAddress, 
                    string GeoCoordinateImage, 
                    object userState) {
            if ((this.InsertLandCoordinatesOperationCompleted == null)) {
                this.InsertLandCoordinatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertLandCoordinatesOperationCompleted);
            }
            this.InvokeAsync("InsertLandCoordinates", new object[] {
                        userid,
                        password,
                        DistrictCode,
                        MandalCode,
                        VillageCode,
                        SurveyNo,
                        KhathaNo,
                        Extent,
                        CRD1,
                        CRD2,
                        CRD3,
                        CRD4,
                        CRD5,
                        CRD6,
                        CRD7,
                        CRD8,
                        CRD9,
                        CRD10,
                        UTM1,
                        UTM2,
                        UTM3,
                        UTM4,
                        UTM5,
                        UTM6,
                        UTM7,
                        UTM8,
                        UTM9,
                        UTM10,
                        Remarks1,
                        Remarks2,
                        Remarks3,
                        Remarks4,
                        Remarks5,
                        Remarks6,
                        Remarks7,
                        Remarks8,
                        Remarks9,
                        Remarks10,
                        CreatedBy,
                        IPAddress,
                        GeoCoordinateImage}, this.InsertLandCoordinatesOperationCompleted, userState);
        }
        
        private void OnInsertLandCoordinatesOperationCompleted(object arg) {
            if ((this.InsertLandCoordinatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertLandCoordinatesCompleted(this, new InsertLandCoordinatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_LandCoordinates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_LandCoordinates(string userid, string password, string MandalId, string villageId, string SurveyNo, string KhathaNo) {
            object[] results = this.Invoke("Get_LandCoordinates", new object[] {
                        userid,
                        password,
                        MandalId,
                        villageId,
                        SurveyNo,
                        KhathaNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_LandCoordinatesAsync(string userid, string password, string MandalId, string villageId, string SurveyNo, string KhathaNo) {
            this.Get_LandCoordinatesAsync(userid, password, MandalId, villageId, SurveyNo, KhathaNo, null);
        }
        
        /// <remarks/>
        public void Get_LandCoordinatesAsync(string userid, string password, string MandalId, string villageId, string SurveyNo, string KhathaNo, object userState) {
            if ((this.Get_LandCoordinatesOperationCompleted == null)) {
                this.Get_LandCoordinatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_LandCoordinatesOperationCompleted);
            }
            this.InvokeAsync("Get_LandCoordinates", new object[] {
                        userid,
                        password,
                        MandalId,
                        villageId,
                        SurveyNo,
                        KhathaNo}, this.Get_LandCoordinatesOperationCompleted, userState);
        }
        
        private void OnGet_LandCoordinatesOperationCompleted(object arg) {
            if ((this.Get_LandCoordinatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_LandCoordinatesCompleted(this, new Get_LandCoordinatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPopulateVillages_New", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPopulateVillages_New(string userid, string password, string Version) {
            object[] results = this.Invoke("GetPopulateVillages_New", new object[] {
                        userid,
                        password,
                        Version});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPopulateVillages_NewAsync(string userid, string password, string Version) {
            this.GetPopulateVillages_NewAsync(userid, password, Version, null);
        }
        
        /// <remarks/>
        public void GetPopulateVillages_NewAsync(string userid, string password, string Version, object userState) {
            if ((this.GetPopulateVillages_NewOperationCompleted == null)) {
                this.GetPopulateVillages_NewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPopulateVillages_NewOperationCompleted);
            }
            this.InvokeAsync("GetPopulateVillages_New", new object[] {
                        userid,
                        password,
                        Version}, this.GetPopulateVillages_NewOperationCompleted, userState);
        }
        
        private void OnGetPopulateVillages_NewOperationCompleted(object arg) {
            if ((this.GetPopulateVillages_NewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPopulateVillages_NewCompleted(this, new GetPopulateVillages_NewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertLCData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertLCData(string userid, string Password, string MOBINPUTJSON) {
            object[] results = this.Invoke("InsertLCData", new object[] {
                        userid,
                        Password,
                        MOBINPUTJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertLCDataAsync(string userid, string Password, string MOBINPUTJSON) {
            this.InsertLCDataAsync(userid, Password, MOBINPUTJSON, null);
        }
        
        /// <remarks/>
        public void InsertLCDataAsync(string userid, string Password, string MOBINPUTJSON, object userState) {
            if ((this.InsertLCDataOperationCompleted == null)) {
                this.InsertLCDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertLCDataOperationCompleted);
            }
            this.InvokeAsync("InsertLCData", new object[] {
                        userid,
                        Password,
                        MOBINPUTJSON}, this.InsertLCDataOperationCompleted, userState);
        }
        
        private void OnInsertLCDataOperationCompleted(object arg) {
            if ((this.InsertLCDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertLCDataCompleted(this, new InsertLCDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLandGeoCoordinatesDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLandGeoCoordinatesDetails(string userid, string password) {
            object[] results = this.Invoke("GetLandGeoCoordinatesDetails", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLandGeoCoordinatesDetailsAsync(string userid, string password) {
            this.GetLandGeoCoordinatesDetailsAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void GetLandGeoCoordinatesDetailsAsync(string userid, string password, object userState) {
            if ((this.GetLandGeoCoordinatesDetailsOperationCompleted == null)) {
                this.GetLandGeoCoordinatesDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLandGeoCoordinatesDetailsOperationCompleted);
            }
            this.InvokeAsync("GetLandGeoCoordinatesDetails", new object[] {
                        userid,
                        password}, this.GetLandGeoCoordinatesDetailsOperationCompleted, userState);
        }
        
        private void OnGetLandGeoCoordinatesDetailsOperationCompleted(object arg) {
            if ((this.GetLandGeoCoordinatesDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLandGeoCoordinatesDetailsCompleted(this, new GetLandGeoCoordinatesDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLandGeoCoordinatesDetails_new", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetLandGeoCoordinatesDetails_new() {
            this.Invoke("GetLandGeoCoordinatesDetails_new", new object[0]);
        }
        
        /// <remarks/>
        public void GetLandGeoCoordinatesDetails_newAsync() {
            this.GetLandGeoCoordinatesDetails_newAsync(null);
        }
        
        /// <remarks/>
        public void GetLandGeoCoordinatesDetails_newAsync(object userState) {
            if ((this.GetLandGeoCoordinatesDetails_newOperationCompleted == null)) {
                this.GetLandGeoCoordinatesDetails_newOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLandGeoCoordinatesDetails_newOperationCompleted);
            }
            this.InvokeAsync("GetLandGeoCoordinatesDetails_new", new object[0], this.GetLandGeoCoordinatesDetails_newOperationCompleted, userState);
        }
        
        private void OnGetLandGeoCoordinatesDetails_newOperationCompleted(object arg) {
            if ((this.GetLandGeoCoordinatesDetails_newCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLandGeoCoordinatesDetails_newCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPDF() {
            object[] results = this.Invoke("getPDF", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPDFAsync() {
            this.getPDFAsync(null);
        }
        
        /// <remarks/>
        public void getPDFAsync(object userState) {
            if ((this.getPDFOperationCompleted == null)) {
                this.getPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPDFOperationCompleted);
            }
            this.InvokeAsync("getPDF", new object[0], this.getPDFOperationCompleted, userState);
        }
        
        private void OngetPDFOperationCompleted(object arg) {
            if ((this.getPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPDFCompleted(this, new getPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GETAPPSTATUS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GETAPPSTATUS(string userid, string password, string token, string APPNO) {
            object[] results = this.Invoke("GETAPPSTATUS", new object[] {
                        userid,
                        password,
                        token,
                        APPNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETAPPSTATUSAsync(string userid, string password, string token, string APPNO) {
            this.GETAPPSTATUSAsync(userid, password, token, APPNO, null);
        }
        
        /// <remarks/>
        public void GETAPPSTATUSAsync(string userid, string password, string token, string APPNO, object userState) {
            if ((this.GETAPPSTATUSOperationCompleted == null)) {
                this.GETAPPSTATUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETAPPSTATUSOperationCompleted);
            }
            this.InvokeAsync("GETAPPSTATUS", new object[] {
                        userid,
                        password,
                        token,
                        APPNO}, this.GETAPPSTATUSOperationCompleted, userState);
        }
        
        private void OnGETAPPSTATUSOperationCompleted(object arg) {
            if ((this.GETAPPSTATUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETAPPSTATUSCompleted(this, new GETAPPSTATUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GETDATEWISEAPPROVEDLIST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GETDATEWISEAPPROVEDLIST(string userid, string password, string token, string FromDate, string ToDate) {
            object[] results = this.Invoke("GETDATEWISEAPPROVEDLIST", new object[] {
                        userid,
                        password,
                        token,
                        FromDate,
                        ToDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETDATEWISEAPPROVEDLISTAsync(string userid, string password, string token, string FromDate, string ToDate) {
            this.GETDATEWISEAPPROVEDLISTAsync(userid, password, token, FromDate, ToDate, null);
        }
        
        /// <remarks/>
        public void GETDATEWISEAPPROVEDLISTAsync(string userid, string password, string token, string FromDate, string ToDate, object userState) {
            if ((this.GETDATEWISEAPPROVEDLISTOperationCompleted == null)) {
                this.GETDATEWISEAPPROVEDLISTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETDATEWISEAPPROVEDLISTOperationCompleted);
            }
            this.InvokeAsync("GETDATEWISEAPPROVEDLIST", new object[] {
                        userid,
                        password,
                        token,
                        FromDate,
                        ToDate}, this.GETDATEWISEAPPROVEDLISTOperationCompleted, userState);
        }
        
        private void OnGETDATEWISEAPPROVEDLISTOperationCompleted(object arg) {
            if ((this.GETDATEWISEAPPROVEDLISTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETDATEWISEAPPROVEDLISTCompleted(this, new GETDATEWISEAPPROVEDLISTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTokenSSO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTokenSSO(string userid, string password) {
            object[] results = this.Invoke("GetTokenSSO", new object[] {
                        userid,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTokenSSOAsync(string userid, string password) {
            this.GetTokenSSOAsync(userid, password, null);
        }
        
        /// <remarks/>
        public void GetTokenSSOAsync(string userid, string password, object userState) {
            if ((this.GetTokenSSOOperationCompleted == null)) {
                this.GetTokenSSOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTokenSSOOperationCompleted);
            }
            this.InvokeAsync("GetTokenSSO", new object[] {
                        userid,
                        password}, this.GetTokenSSOOperationCompleted, userState);
        }
        
        private void OnGetTokenSSOOperationCompleted(object arg) {
            if ((this.GetTokenSSOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTokenSSOCompleted(this, new GetTokenSSOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HousePattaBO {
        
        private string volunteerIdField;
        
        private string vNameField;
        
        private long vMobileField;
        
        private long vAadhaarField;
        
        private string sachivalayamCodenoField;
        
        private string sachivalayamNameField;
        
        private long bAdhaarnoField;
        
        private string benficiaryNameField;
        
        private string appnoField;
        
        private long bmobileField;
        
        private string relationIDField;
        
        private string relationNameField;
        
        private int ageField;
        
        private char genderField;
        
        private string religionField;
        
        private int isPhysChallField;
        
        private string casteIDField;
        
        private string subCasteIDField;
        
        private string occupationField;
        
        private string otherOccupationField;
        
        private string housenoField;
        
        private string streetField;
        
        private int districtIDField;
        
        private int mandalIDField;
        
        private int villageIDField;
        
        private int panchayathIDField;
        
        private int pincodeField;
        
        private int isRationField;
        
        private string rationcardnoField;
        
        private int isHouseField;
        
        private int isHouseSiteField;
        
        private int isHousingSchemeField;
        
        private int isHouseSiteSchemeField;
        
        private int isLandField;
        
        private string cityField;
        
        private string wardNameField;
        
        private int isIncomeField;
        
        private int isPMAYField;
        
        private int pMAYBenefitSchemeIDField;
        
        private int isAHPAllotmentReceivedField;
        
        private string aHPAllotmentDetailsField;
        
        private string uSERIDField;
        
        private int isVolunteerApprovedField;
        
        private string fileField;
        
        private string systemIPField;
        
        private string mandaltypeIDField;
        
        /// <remarks/>
        public string VolunteerId {
            get {
                return this.volunteerIdField;
            }
            set {
                this.volunteerIdField = value;
            }
        }
        
        /// <remarks/>
        public string VName {
            get {
                return this.vNameField;
            }
            set {
                this.vNameField = value;
            }
        }
        
        /// <remarks/>
        public long VMobile {
            get {
                return this.vMobileField;
            }
            set {
                this.vMobileField = value;
            }
        }
        
        /// <remarks/>
        public long VAadhaar {
            get {
                return this.vAadhaarField;
            }
            set {
                this.vAadhaarField = value;
            }
        }
        
        /// <remarks/>
        public string SachivalayamCodeno {
            get {
                return this.sachivalayamCodenoField;
            }
            set {
                this.sachivalayamCodenoField = value;
            }
        }
        
        /// <remarks/>
        public string SachivalayamName {
            get {
                return this.sachivalayamNameField;
            }
            set {
                this.sachivalayamNameField = value;
            }
        }
        
        /// <remarks/>
        public long BAdhaarno {
            get {
                return this.bAdhaarnoField;
            }
            set {
                this.bAdhaarnoField = value;
            }
        }
        
        /// <remarks/>
        public string BenficiaryName {
            get {
                return this.benficiaryNameField;
            }
            set {
                this.benficiaryNameField = value;
            }
        }
        
        /// <remarks/>
        public string Appno {
            get {
                return this.appnoField;
            }
            set {
                this.appnoField = value;
            }
        }
        
        /// <remarks/>
        public long Bmobile {
            get {
                return this.bmobileField;
            }
            set {
                this.bmobileField = value;
            }
        }
        
        /// <remarks/>
        public string RelationID {
            get {
                return this.relationIDField;
            }
            set {
                this.relationIDField = value;
            }
        }
        
        /// <remarks/>
        public string RelationName {
            get {
                return this.relationNameField;
            }
            set {
                this.relationNameField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public char Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public int isPhysChall {
            get {
                return this.isPhysChallField;
            }
            set {
                this.isPhysChallField = value;
            }
        }
        
        /// <remarks/>
        public string CasteID {
            get {
                return this.casteIDField;
            }
            set {
                this.casteIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubCasteID {
            get {
                return this.subCasteIDField;
            }
            set {
                this.subCasteIDField = value;
            }
        }
        
        /// <remarks/>
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        public string OtherOccupation {
            get {
                return this.otherOccupationField;
            }
            set {
                this.otherOccupationField = value;
            }
        }
        
        /// <remarks/>
        public string Houseno {
            get {
                return this.housenoField;
            }
            set {
                this.housenoField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public int DistrictID {
            get {
                return this.districtIDField;
            }
            set {
                this.districtIDField = value;
            }
        }
        
        /// <remarks/>
        public int MandalID {
            get {
                return this.mandalIDField;
            }
            set {
                this.mandalIDField = value;
            }
        }
        
        /// <remarks/>
        public int VillageID {
            get {
                return this.villageIDField;
            }
            set {
                this.villageIDField = value;
            }
        }
        
        /// <remarks/>
        public int PanchayathID {
            get {
                return this.panchayathIDField;
            }
            set {
                this.panchayathIDField = value;
            }
        }
        
        /// <remarks/>
        public int Pincode {
            get {
                return this.pincodeField;
            }
            set {
                this.pincodeField = value;
            }
        }
        
        /// <remarks/>
        public int isRation {
            get {
                return this.isRationField;
            }
            set {
                this.isRationField = value;
            }
        }
        
        /// <remarks/>
        public string Rationcardno {
            get {
                return this.rationcardnoField;
            }
            set {
                this.rationcardnoField = value;
            }
        }
        
        /// <remarks/>
        public int isHouse {
            get {
                return this.isHouseField;
            }
            set {
                this.isHouseField = value;
            }
        }
        
        /// <remarks/>
        public int isHouseSite {
            get {
                return this.isHouseSiteField;
            }
            set {
                this.isHouseSiteField = value;
            }
        }
        
        /// <remarks/>
        public int isHousingScheme {
            get {
                return this.isHousingSchemeField;
            }
            set {
                this.isHousingSchemeField = value;
            }
        }
        
        /// <remarks/>
        public int isHouseSiteScheme {
            get {
                return this.isHouseSiteSchemeField;
            }
            set {
                this.isHouseSiteSchemeField = value;
            }
        }
        
        /// <remarks/>
        public int isLand {
            get {
                return this.isLandField;
            }
            set {
                this.isLandField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string WardName {
            get {
                return this.wardNameField;
            }
            set {
                this.wardNameField = value;
            }
        }
        
        /// <remarks/>
        public int isIncome {
            get {
                return this.isIncomeField;
            }
            set {
                this.isIncomeField = value;
            }
        }
        
        /// <remarks/>
        public int isPMAY {
            get {
                return this.isPMAYField;
            }
            set {
                this.isPMAYField = value;
            }
        }
        
        /// <remarks/>
        public int PMAYBenefitSchemeID {
            get {
                return this.pMAYBenefitSchemeIDField;
            }
            set {
                this.pMAYBenefitSchemeIDField = value;
            }
        }
        
        /// <remarks/>
        public int isAHPAllotmentReceived {
            get {
                return this.isAHPAllotmentReceivedField;
            }
            set {
                this.isAHPAllotmentReceivedField = value;
            }
        }
        
        /// <remarks/>
        public string AHPAllotmentDetails {
            get {
                return this.aHPAllotmentDetailsField;
            }
            set {
                this.aHPAllotmentDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        public int isVolunteerApproved {
            get {
                return this.isVolunteerApprovedField;
            }
            set {
                this.isVolunteerApprovedField = value;
            }
        }
        
        /// <remarks/>
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public string SystemIP {
            get {
                return this.systemIPField;
            }
            set {
                this.systemIPField = value;
            }
        }
        
        /// <remarks/>
        public string MandaltypeID {
            get {
                return this.mandaltypeIDField;
            }
            set {
                this.mandaltypeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GVS_CITIZENSERVICESCOUNTCompletedEventHandler(object sender, GVS_CITIZENSERVICESCOUNTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GVS_CITIZENSERVICESCOUNTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GVS_CITIZENSERVICESCOUNTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTokenCompletedEventHandler(object sender, GetTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void HouseSitePattaApplication_AddCompletedEventHandler(object sender, HouseSitePattaApplication_AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HouseSitePattaApplication_AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HouseSitePattaApplication_AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void HouseSitePattaApplication_Add2CompletedEventHandler(object sender, HouseSitePattaApplication_Add2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HouseSitePattaApplication_Add2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HouseSitePattaApplication_Add2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void HouseSitePattaApplication_StatusCompletedEventHandler(object sender, HouseSitePattaApplication_StatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HouseSitePattaApplication_StatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HouseSitePattaApplication_StatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetHSP_APP_StatusCompletedEventHandler(object sender, GetHSP_APP_StatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHSP_APP_StatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHSP_APP_StatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetHSP_APP_ByDate_StatusCompletedEventHandler(object sender, GetHSP_APP_ByDate_StatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHSP_APP_ByDate_StatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHSP_APP_ByDate_StatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPopulateVillagesCompletedEventHandler(object sender, GetPopulateVillagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPopulateVillagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPopulateVillagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPopulateSurveyNumbersCompletedEventHandler(object sender, GetPopulateSurveyNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPopulateSurveyNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPopulateSurveyNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPopulateKhataNumbersCompletedEventHandler(object sender, GetPopulateKhataNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPopulateKhataNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPopulateKhataNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InsertLandCoordinatesCompletedEventHandler(object sender, InsertLandCoordinatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertLandCoordinatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertLandCoordinatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Get_LandCoordinatesCompletedEventHandler(object sender, Get_LandCoordinatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_LandCoordinatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_LandCoordinatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPopulateVillages_NewCompletedEventHandler(object sender, GetPopulateVillages_NewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPopulateVillages_NewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPopulateVillages_NewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InsertLCDataCompletedEventHandler(object sender, InsertLCDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertLCDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertLCDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetLandGeoCoordinatesDetailsCompletedEventHandler(object sender, GetLandGeoCoordinatesDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLandGeoCoordinatesDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLandGeoCoordinatesDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetLandGeoCoordinatesDetails_newCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getPDFCompletedEventHandler(object sender, getPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GETAPPSTATUSCompletedEventHandler(object sender, GETAPPSTATUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETAPPSTATUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETAPPSTATUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GETDATEWISEAPPROVEDLISTCompletedEventHandler(object sender, GETDATEWISEAPPROVEDLISTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETDATEWISEAPPROVEDLISTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETDATEWISEAPPROVEDLISTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTokenSSOCompletedEventHandler(object sender, GetTokenSSOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTokenSSOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTokenSSOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591