//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gswsBackendAPI.EPantaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="getVillageDataBinding", Namespace="urn:http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php")]
    public partial class getVillageData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallgetVillageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVillageSurveyNoDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVillageAadharDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public getVillageData() {
            this.Url = global::gswsBackendAPI.Properties.Settings.Default.gswsBackendAPI_EPantaService_getVillageData;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallgetVillageDataCompletedEventHandler CallgetVillageDataCompleted;
        
        /// <remarks/>
        public event getVillageSurveyNoDataCompletedEventHandler getVillageSurveyNoDataCompleted;
        
        /// <remarks/>
        public event getVillageAadharDataCompletedEventHandler getVillageAadharDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php/getVill" +
            "ageData", RequestNamespace="http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php", ResponseNamespace="http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("c")]
        public string CallgetVillageData(string UserName, string Password, string District, string Mandal, string Village) {
            object[] results = this.Invoke("CallgetVillageData", new object[] {
                        UserName,
                        Password,
                        District,
                        Mandal,
                        Village});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CallgetVillageDataAsync(string UserName, string Password, string District, string Mandal, string Village) {
            this.CallgetVillageDataAsync(UserName, Password, District, Mandal, Village, null);
        }
        
        /// <remarks/>
        public void CallgetVillageDataAsync(string UserName, string Password, string District, string Mandal, string Village, object userState) {
            if ((this.CallgetVillageDataOperationCompleted == null)) {
                this.CallgetVillageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallgetVillageDataOperationCompleted);
            }
            this.InvokeAsync("CallgetVillageData", new object[] {
                        UserName,
                        Password,
                        District,
                        Mandal,
                        Village}, this.CallgetVillageDataOperationCompleted, userState);
        }
        
        private void OnCallgetVillageDataOperationCompleted(object arg) {
            if ((this.CallgetVillageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallgetVillageDataCompleted(this, new CallgetVillageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php/getVill" +
            "ageSurveyNoData", RequestNamespace="http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php", ResponseNamespace="http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("c")]
        public string getVillageSurveyNoData(string UserName, string Password, string District, string Mandal, string Village, string SurveyNo) {
            object[] results = this.Invoke("getVillageSurveyNoData", new object[] {
                        UserName,
                        Password,
                        District,
                        Mandal,
                        Village,
                        SurveyNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVillageSurveyNoDataAsync(string UserName, string Password, string District, string Mandal, string Village, string SurveyNo) {
            this.getVillageSurveyNoDataAsync(UserName, Password, District, Mandal, Village, SurveyNo, null);
        }
        
        /// <remarks/>
        public void getVillageSurveyNoDataAsync(string UserName, string Password, string District, string Mandal, string Village, string SurveyNo, object userState) {
            if ((this.getVillageSurveyNoDataOperationCompleted == null)) {
                this.getVillageSurveyNoDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVillageSurveyNoDataOperationCompleted);
            }
            this.InvokeAsync("getVillageSurveyNoData", new object[] {
                        UserName,
                        Password,
                        District,
                        Mandal,
                        Village,
                        SurveyNo}, this.getVillageSurveyNoDataOperationCompleted, userState);
        }
        
        private void OngetVillageSurveyNoDataOperationCompleted(object arg) {
            if ((this.getVillageSurveyNoDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVillageSurveyNoDataCompleted(this, new getVillageSurveyNoDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php/getVill" +
            "ageAadharData", RequestNamespace="http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php", ResponseNamespace="http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php")]
        [return: System.Xml.Serialization.SoapElementAttribute("c")]
        public string getVillageAadharData(string UserName, string Password, string District, string Mandal, string Village, string Aadhar) {
            object[] results = this.Invoke("getVillageAadharData", new object[] {
                        UserName,
                        Password,
                        District,
                        Mandal,
                        Village,
                        Aadhar});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVillageAadharDataAsync(string UserName, string Password, string District, string Mandal, string Village, string Aadhar) {
            this.getVillageAadharDataAsync(UserName, Password, District, Mandal, Village, Aadhar, null);
        }
        
        /// <remarks/>
        public void getVillageAadharDataAsync(string UserName, string Password, string District, string Mandal, string Village, string Aadhar, object userState) {
            if ((this.getVillageAadharDataOperationCompleted == null)) {
                this.getVillageAadharDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVillageAadharDataOperationCompleted);
            }
            this.InvokeAsync("getVillageAadharData", new object[] {
                        UserName,
                        Password,
                        District,
                        Mandal,
                        Village,
                        Aadhar}, this.getVillageAadharDataOperationCompleted, userState);
        }
        
        private void OngetVillageAadharDataOperationCompleted(object arg) {
            if ((this.getVillageAadharDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVillageAadharDataCompleted(this, new getVillageAadharDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CallgetVillageDataCompletedEventHandler(object sender, CallgetVillageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallgetVillageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallgetVillageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getVillageSurveyNoDataCompletedEventHandler(object sender, getVillageSurveyNoDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVillageSurveyNoDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVillageSurveyNoDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getVillageAadharDataCompletedEventHandler(object sender, getVillageAadharDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVillageAadharDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVillageAadharDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591