//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gswsBackendAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uat.meeseva.gov.in/MeesevaMobileWebService/MeesevaMobileWebservice.asmx")]
        public string gswsBackendAPI_UatMeeseva_MeesevaMobileWebservice {
            get {
                return ((string)(this["gswsBackendAPI_UatMeeseva_MeesevaMobileWebservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apwaqf.aponline.gov.in/minorityservice.asmx")]
        public string gswsBackendAPI_minorityservice_MinorityService {
            get {
                return ((string)(this["gswsBackendAPI_minorityservice_MinorityService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uat.meeseva.gov.in/meesevawebservice/meesevawebservice.asmx")]
        public string gswsBackendAPI_MeesevaWebUAT_MeeSevaWebService {
            get {
                return ((string)(this["gswsBackendAPI_MeesevaWebUAT_MeeSevaWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bima.ap.gov.in/services/vvclaimstatus.asmx")]
        public string gswsBackendAPI_SerpBima_vvclaimstatus {
            get {
                return ((string)(this["gswsBackendAPI_SerpBima_vvclaimstatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bima.ap.gov.in/services/Claimregistration.asmx")]
        public string gswsBackendAPI_ClaimRegistration_ClaimRegistration {
            get {
                return ((string)(this["gswsBackendAPI_ClaimRegistration_ClaimRegistration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pushpm86.sps.ap.gov.in/EDACSMS/SMSService.asmx")]
        public string gswsBackendAPI_SMSService_SMSService {
            get {
                return ((string)(this["gswsBackendAPI_SMSService_SMSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://tptuat.aponline.gov.in/APRDC/ComplaintsSearchService.asmx")]
        public string gswsBackendAPI_RoadsComplaint_StatusCheck_ComplaintsSearchService {
            get {
                return ((string)(this["gswsBackendAPI_RoadsComplaint_StatusCheck_ComplaintsSearchService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uatwebland.ap.gov.in/wspahani.asmx")]
        public string gswsBackendAPI_WebLand_Revenue_WSPahani {
            get {
                return ((string)(this["gswsBackendAPI_WebLand_Revenue_WSPahani"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sadarem.ap.gov.in:443/Sadaremwebservice/ValidSadaremid")]
        public string gswsBackendAPI_Sadarem_ValidSadaremidService {
            get {
                return ((string)(this["gswsBackendAPI_Sadarem_ValidSadaremidService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://103.210.75.132/AreaSownServiceDetails/kharif2019ServiceDetails.php")]
        public string gswsBackendAPI_EPantaService_getVillageData {
            get {
                return ((string)(this["gswsBackendAPI_EPantaService_getVillageData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://push83.sps.ap.gov.in/WEBEKYCOTP/WREKYCOTP.asmx")]
        public string gswsBackendAPI_WRServiceAadhaarOTP83_WREKYCOTP {
            get {
                return ((string)(this["gswsBackendAPI_WRServiceAadhaarOTP83_WREKYCOTP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://tptuat.aponline.gov.in/AHAService/AHAServices.asmx")]
        public string gswsBackendAPI_Animal_AHAServices {
            get {
                return ((string)(this["gswsBackendAPI_Animal_AHAServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://103.14.188.80:8080/RWMService/services/ServicesRWMS.ServicesRWMSHttpSoap11" +
            "Endpoint/")]
        public string gswsBackendAPI_walletOnePaymentService_ServicesRWMS {
            get {
                return ((string)(this["gswsBackendAPI_walletOnePaymentService_ServicesRWMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://aprdc.ap.gov.in/ComplaintsSearchService.asmx")]
        public string gswsBackendAPI_Transport_ComplaintsStatusCheck_ComplaintsSearchService {
            get {
                return ((string)(this["gswsBackendAPI_Transport_ComplaintsStatusCheck_ComplaintsSearchService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apdept.meeseva.gov.in/meesevawebservice/meesevawebservice.asmx")]
        public string gswsBackendAPI_MeesevaProductionService_MeeSevaWebService {
            get {
                return ((string)(this["gswsBackendAPI_MeesevaProductionService_MeeSevaWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://103.14.188.80:8080/RWMService/services/ServicesRWMS.ServicesRWMSHttpSoap11" +
            "Endpoint/")]
        public string gswsBackendAPI_RamInfoService_ServicesRWMS {
            get {
                return ((string)(this["gswsBackendAPI_RamInfoService_ServicesRWMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://navaratnalu-housesites.ap.gov.in/WebService/API.asmx")]
        public string gswsBackendAPI_HousesiteWebservice_API {
            get {
                return ((string)(this["gswsBackendAPI_HousesiteWebservice_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.21.84.205:8080/RWMService/services/ServicesRWMS.ServicesRWMSHttpSoap11" +
            "Endpoint/")]
        public string gswsBackendAPI_RaminfoprodServce_ServicesRWMS {
            get {
                return ((string)(this["gswsBackendAPI_RaminfoprodServce_ServicesRWMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uat.gramawardsachivalayam.ap.gov.in/SMSAPP/SMSService.asmx")]
        public string gswsBackendAPI_UATSMSService_SMSService {
            get {
                return ((string)(this["gswsBackendAPI_UATSMSService_SMSService"]));
            }
        }
    }
}
