//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gswsBackendAPI.minorityservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MinorityServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MinorityService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHonorariumToImamAndMouzansDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWomenDivorcedDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MinorityService() {
            this.Url = global::gswsBackendAPI.Properties.Settings.Default.gswsBackendAPI_minorityservice_MinorityService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHonorariumToImamAndMouzansDetailsCompletedEventHandler GetHonorariumToImamAndMouzansDetailsCompleted;
        
        /// <remarks/>
        public event GetWomenDivorcedDetailsCompletedEventHandler GetWomenDivorcedDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHonorariumToImamAndMouzansDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHonorariumToImamAndMouzansDetails(string BeneficiaryCode) {
            object[] results = this.Invoke("GetHonorariumToImamAndMouzansDetails", new object[] {
                        BeneficiaryCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHonorariumToImamAndMouzansDetailsAsync(string BeneficiaryCode) {
            this.GetHonorariumToImamAndMouzansDetailsAsync(BeneficiaryCode, null);
        }
        
        /// <remarks/>
        public void GetHonorariumToImamAndMouzansDetailsAsync(string BeneficiaryCode, object userState) {
            if ((this.GetHonorariumToImamAndMouzansDetailsOperationCompleted == null)) {
                this.GetHonorariumToImamAndMouzansDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHonorariumToImamAndMouzansDetailsOperationCompleted);
            }
            this.InvokeAsync("GetHonorariumToImamAndMouzansDetails", new object[] {
                        BeneficiaryCode}, this.GetHonorariumToImamAndMouzansDetailsOperationCompleted, userState);
        }
        
        private void OnGetHonorariumToImamAndMouzansDetailsOperationCompleted(object arg) {
            if ((this.GetHonorariumToImamAndMouzansDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHonorariumToImamAndMouzansDetailsCompleted(this, new GetHonorariumToImamAndMouzansDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWomenDivorcedDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetWomenDivorcedDetails(string MCNO) {
            object[] results = this.Invoke("GetWomenDivorcedDetails", new object[] {
                        MCNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetWomenDivorcedDetailsAsync(string MCNO) {
            this.GetWomenDivorcedDetailsAsync(MCNO, null);
        }
        
        /// <remarks/>
        public void GetWomenDivorcedDetailsAsync(string MCNO, object userState) {
            if ((this.GetWomenDivorcedDetailsOperationCompleted == null)) {
                this.GetWomenDivorcedDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWomenDivorcedDetailsOperationCompleted);
            }
            this.InvokeAsync("GetWomenDivorcedDetails", new object[] {
                        MCNO}, this.GetWomenDivorcedDetailsOperationCompleted, userState);
        }
        
        private void OnGetWomenDivorcedDetailsOperationCompleted(object arg) {
            if ((this.GetWomenDivorcedDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWomenDivorcedDetailsCompleted(this, new GetWomenDivorcedDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetHonorariumToImamAndMouzansDetailsCompletedEventHandler(object sender, GetHonorariumToImamAndMouzansDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHonorariumToImamAndMouzansDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHonorariumToImamAndMouzansDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetWomenDivorcedDetailsCompletedEventHandler(object sender, GetWomenDivorcedDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWomenDivorcedDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWomenDivorcedDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591