using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace gswsBackendAPI.DL.CommonHel
{
	public static class DepartmentEnum
	{
		public enum Department
		{
			Agriculture_and_Marketing = 11,
			Animal_Husbandry_Dairy_Development_and_Fisheries = 12,
			Backward_Classes_Welfar = 13,
			Environment_Forest_Science_and_Technology = 14,
			Human_Resources_Higher_Education = 15,
			Energy = 16,
			Human_Resources_School_Education = 17,
			Consumer_Affairs_Food_and_Civil_Supplies = 18,
			Chief_Electoral_Officer = 19,
			Health_Medical_Family_Welfare = 20,
			Home = 21,
			Housing = 22,
			Water_Resources = 23,
			Industries_Infrastructure_Investment_and_Commerce = 24,
			Information_Technology_Electronics_and_Communications = 25,
			Labour_Employment_Training_and_Factories = 26,
			Municipal_Administration_and_Urban_Development = 27,
			Minorities_Welfare = 28,
			Public_Enterprises = 29,
			Planning = 30,
			Panchayat_Raj_and_Rural_Development = 31,
			Disaster_Management = 32,
			Revenue = 33,
			Real_Time_Governance = 34,
			Skill_Development_Entrepreneurship_and_Innovation = 35,
			Social_Tribal_Welfare = 36,
			Transport_Roads_and_Buildings = 37,
			Women_Children_Disabled_and_Senior_Citizens = 38,
			Youth_Advancement_Tourism_and_Culture = 39,
			Law = 40,

		}
		public enum HOD
		{
			AP_Tourism_Development_Corporation = 3905,
			APSRTC = 3703,
			APHOUSING = 2201,
			SkillDevelopment = 3501,
			YouthServices = 3904,
			Agriculture = 1101,
			Horticulture = 1102,
			Sericulture = 1103,
			Marketing = 1104,
			Cooperation_and_Cooperative_Societies = 1105,
			Animal_Husbandry = 1201,
			Fisheries = 1202,
			BC_Welfare = 1301,
			Forest_PCCF = 1401,
			Technical_Education = 1501,
			Collegiate_Education = 1502,
			State_Archives = 1503,
			Oriental_Manscripts = 1505,
			Electrical_Safety = 1601,
			State_Ports = 2405,
			School_Education = 1701,
			Adult_Education = 1703,
			Civil_Supplies = 1801,
			Legal_Metrology = 1802,
			Public_Health = 2002,
			Family_Welfare = 2003,
			Ayush = 2005,
			Drugs_Control_Administration = 2006,
			Police_DGP = 2101,
			Prisons_Correctional_Services = 2102,
			Fire_Services = 2104,
			Sainik_Welfare = 2105,
			Special_Protection_Force = 2106,
			Ground_Water = 2302,
			Water_Resources_E_in_C = 2303,
			Resettlement_and_Rehabilitation = 2304,
			Handlooms_Textiles = 2402,
			Mines_and_Geology = 2403,
			Electronics_Delivery_Services = 2501,
			Labour = 2602,
			Factories = 2603,
			Insurance_Medical_Services = 2604,
			Boilers = 2605,
			Town_and_Country_Planning = 2702,
			Minorities_Welfare = 2801,
			Economics_and_Statistics = 3001,
			Panchayati_Raj_Engineering = 3102,
			Rural_Water_Supply_ngineering = 3104,
			Commercial_Taxes = 3302,
			Prohibition_and_Excise = 3303,
			Endowment = 3305,
			Registration_and_Stamps = 3306,
			Social_Welfare = 3601,
			Tribal_Welfare_engineering = 3603,
			Transport = 3702,
			Women_Development_and_Child_welfare = 3801,
			Juvenile_Welfare_Correctional_services = 3803,
			SPORTS = 3901,
			National_Cadet_Corps = 3902,
			Intermediate_Education = 1504,
			Publication = 1702,
			Public_Libraries = 1704,
			Medical_Education = 2001,
			Institute_of_Preventive_edicine_IPM_Food_Safety = 2004,
			Printing_and_stationery = 2103,
			Command_Area_Development_Authority_CADA = 2301,
			Industries_Commerce_and_Export_Promotion = 2401,
			Sugar_and_Cane = 2404,
			Employment_and_Training = 2601,
			Municipal_Administration = 2701,
			Public_Health_Engineering = 2703,
			Panchayati_Raj = 3101,
			Rural_Development = 3103,
			Revenue_CCLA = 3301,
			Survey_Settlements_and_Land_Records = 3304,
			Tribal_Welfare = 3602,
			Roads_and_Buildings_E_in_C = 3701,
			Differently_Abled, Senior_itizens_Transgender = 3802,
			Archaeology_and_Museums = 3903,
			PRAJASADHIKARA_SURVEY = 3401,
			Law = 4001,
			Spandana = 3402


		}
	}
}