//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gswsBackendAPI.Sadarem {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ValidSadaremidPortBinding", Namespace="http://in.com/")]
    public partial class ValidSadaremidService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback operationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSADAREMDetailsValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSADAREMValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTemparyorpermenantOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDisabilitydetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getcertificatvalidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RTGSSadaremDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkSadaremDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ValidSadaremidService() {
            this.Url = global::gswsBackendAPI.Properties.Settings.Default.gswsBackendAPI_Sadarem_ValidSadaremidService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event operationCompletedEventHandler operationCompleted;
        
        /// <remarks/>
        public event getSADAREMDetailsValidationCompletedEventHandler getSADAREMDetailsValidationCompleted;
        
        /// <remarks/>
        public event getSADAREMValidationCompletedEventHandler getSADAREMValidationCompleted;
        
        /// <remarks/>
        public event getTemparyorpermenantCompletedEventHandler getTemparyorpermenantCompleted;
        
        /// <remarks/>
        public event getDisabilitydetailsCompletedEventHandler getDisabilitydetailsCompleted;
        
        /// <remarks/>
        public event getcertificatvalidCompletedEventHandler getcertificatvalidCompleted;
        
        /// <remarks/>
        public event RTGSSadaremDataCompletedEventHandler RTGSSadaremDataCompleted;
        
        /// <remarks/>
        public event checkSadaremDetailsCompletedEventHandler checkSadaremDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation() {
            object[] results = this.Invoke("operation", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void operationAsync() {
            this.operationAsync(null);
        }
        
        /// <remarks/>
        public void operationAsync(object userState) {
            if ((this.operationOperationCompleted == null)) {
                this.operationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoperationOperationCompleted);
            }
            this.InvokeAsync("operation", new object[0], this.operationOperationCompleted, userState);
        }
        
        private void OnoperationOperationCompleted(object arg) {
            if ((this.operationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.operationCompleted(this, new operationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getSADAREMDetailsValidation([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string personcode) {
            object[] results = this.Invoke("getSADAREMDetailsValidation", new object[] {
                        personcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSADAREMDetailsValidationAsync(string personcode) {
            this.getSADAREMDetailsValidationAsync(personcode, null);
        }
        
        /// <remarks/>
        public void getSADAREMDetailsValidationAsync(string personcode, object userState) {
            if ((this.getSADAREMDetailsValidationOperationCompleted == null)) {
                this.getSADAREMDetailsValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSADAREMDetailsValidationOperationCompleted);
            }
            this.InvokeAsync("getSADAREMDetailsValidation", new object[] {
                        personcode}, this.getSADAREMDetailsValidationOperationCompleted, userState);
        }
        
        private void OngetSADAREMDetailsValidationOperationCompleted(object arg) {
            if ((this.getSADAREMDetailsValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSADAREMDetailsValidationCompleted(this, new getSADAREMDetailsValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getSADAREMValidation([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string personcode) {
            object[] results = this.Invoke("getSADAREMValidation", new object[] {
                        personcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSADAREMValidationAsync(string personcode) {
            this.getSADAREMValidationAsync(personcode, null);
        }
        
        /// <remarks/>
        public void getSADAREMValidationAsync(string personcode, object userState) {
            if ((this.getSADAREMValidationOperationCompleted == null)) {
                this.getSADAREMValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSADAREMValidationOperationCompleted);
            }
            this.InvokeAsync("getSADAREMValidation", new object[] {
                        personcode}, this.getSADAREMValidationOperationCompleted, userState);
        }
        
        private void OngetSADAREMValidationOperationCompleted(object arg) {
            if ((this.getSADAREMValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSADAREMValidationCompleted(this, new getSADAREMValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getTemparyorpermenant([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string personcode) {
            object[] results = this.Invoke("getTemparyorpermenant", new object[] {
                        personcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTemparyorpermenantAsync(string personcode) {
            this.getTemparyorpermenantAsync(personcode, null);
        }
        
        /// <remarks/>
        public void getTemparyorpermenantAsync(string personcode, object userState) {
            if ((this.getTemparyorpermenantOperationCompleted == null)) {
                this.getTemparyorpermenantOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTemparyorpermenantOperationCompleted);
            }
            this.InvokeAsync("getTemparyorpermenant", new object[] {
                        personcode}, this.getTemparyorpermenantOperationCompleted, userState);
        }
        
        private void OngetTemparyorpermenantOperationCompleted(object arg) {
            if ((this.getTemparyorpermenantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTemparyorpermenantCompleted(this, new getTemparyorpermenantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getDisabilitydetails([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string personcode) {
            object[] results = this.Invoke("getDisabilitydetails", new object[] {
                        personcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDisabilitydetailsAsync(string personcode) {
            this.getDisabilitydetailsAsync(personcode, null);
        }
        
        /// <remarks/>
        public void getDisabilitydetailsAsync(string personcode, object userState) {
            if ((this.getDisabilitydetailsOperationCompleted == null)) {
                this.getDisabilitydetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDisabilitydetailsOperationCompleted);
            }
            this.InvokeAsync("getDisabilitydetails", new object[] {
                        personcode}, this.getDisabilitydetailsOperationCompleted, userState);
        }
        
        private void OngetDisabilitydetailsOperationCompleted(object arg) {
            if ((this.getDisabilitydetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDisabilitydetailsCompleted(this, new getDisabilitydetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getcertificatvalid([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string personcode) {
            object[] results = this.Invoke("getcertificatvalid", new object[] {
                        personcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getcertificatvalidAsync(string personcode) {
            this.getcertificatvalidAsync(personcode, null);
        }
        
        /// <remarks/>
        public void getcertificatvalidAsync(string personcode, object userState) {
            if ((this.getcertificatvalidOperationCompleted == null)) {
                this.getcertificatvalidOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetcertificatvalidOperationCompleted);
            }
            this.InvokeAsync("getcertificatvalid", new object[] {
                        personcode}, this.getcertificatvalidOperationCompleted, userState);
        }
        
        private void OngetcertificatvalidOperationCompleted(object arg) {
            if ((this.getcertificatvalidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getcertificatvalidCompleted(this, new getcertificatvalidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RTGSSadaremData([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fromdate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string todate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password1) {
            object[] results = this.Invoke("RTGSSadaremData", new object[] {
                        fromdate,
                        todate,
                        username1,
                        password1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RTGSSadaremDataAsync(string fromdate, string todate, string username1, string password1) {
            this.RTGSSadaremDataAsync(fromdate, todate, username1, password1, null);
        }
        
        /// <remarks/>
        public void RTGSSadaremDataAsync(string fromdate, string todate, string username1, string password1, object userState) {
            if ((this.RTGSSadaremDataOperationCompleted == null)) {
                this.RTGSSadaremDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRTGSSadaremDataOperationCompleted);
            }
            this.InvokeAsync("RTGSSadaremData", new object[] {
                        fromdate,
                        todate,
                        username1,
                        password1}, this.RTGSSadaremDataOperationCompleted, userState);
        }
        
        private void OnRTGSSadaremDataOperationCompleted(object arg) {
            if ((this.RTGSSadaremDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RTGSSadaremDataCompleted(this, new RTGSSadaremDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://in.com/", ResponseNamespace="http://in.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string checkSadaremDetails([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sadaremId) {
            object[] results = this.Invoke("checkSadaremDetails", new object[] {
                        sadaremId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkSadaremDetailsAsync(string sadaremId) {
            this.checkSadaremDetailsAsync(sadaremId, null);
        }
        
        /// <remarks/>
        public void checkSadaremDetailsAsync(string sadaremId, object userState) {
            if ((this.checkSadaremDetailsOperationCompleted == null)) {
                this.checkSadaremDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckSadaremDetailsOperationCompleted);
            }
            this.InvokeAsync("checkSadaremDetails", new object[] {
                        sadaremId}, this.checkSadaremDetailsOperationCompleted, userState);
        }
        
        private void OncheckSadaremDetailsOperationCompleted(object arg) {
            if ((this.checkSadaremDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkSadaremDetailsCompleted(this, new checkSadaremDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void operationCompletedEventHandler(object sender, operationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class operationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal operationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getSADAREMDetailsValidationCompletedEventHandler(object sender, getSADAREMDetailsValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSADAREMDetailsValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSADAREMDetailsValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getSADAREMValidationCompletedEventHandler(object sender, getSADAREMValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSADAREMValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSADAREMValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getTemparyorpermenantCompletedEventHandler(object sender, getTemparyorpermenantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTemparyorpermenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTemparyorpermenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getDisabilitydetailsCompletedEventHandler(object sender, getDisabilitydetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDisabilitydetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDisabilitydetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getcertificatvalidCompletedEventHandler(object sender, getcertificatvalidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getcertificatvalidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getcertificatvalidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void RTGSSadaremDataCompletedEventHandler(object sender, RTGSSadaremDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RTGSSadaremDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RTGSSadaremDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void checkSadaremDetailsCompletedEventHandler(object sender, checkSadaremDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkSadaremDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkSadaremDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591