//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace gswsBackendAPI.WRServiceAadhaarOTP83 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WREKYCOTPSoap", Namespace="http://tempuri.org/")]
    public partial class WREKYCOTP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback intiateOperationCompleted;
        
        private System.Threading.SendOrPostCallback intiateoldOperationCompleted;
        
        private System.Threading.SendOrPostCallback intiateNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback OtpVerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback OtpVerifyyuvaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOTPyuvaOperationCompleted;
        
        private System.Threading.SendOrPostCallback YUVSendOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback YuvaOtpVerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback YUVSendAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback YuvaOtpVerifyAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback YUVSendOTP174OperationCompleted;
        
        private System.Threading.SendOrPostCallback YuvaOtpVerify174OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WREKYCOTP() {
            this.Url = global::gswsBackendAPI.Properties.Settings.Default.gswsBackendAPI_WRServiceAadhaarOTP83_WREKYCOTP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event intiateCompletedEventHandler intiateCompleted;
        
        /// <remarks/>
        public event intiateoldCompletedEventHandler intiateoldCompleted;
        
        /// <remarks/>
        public event intiateNewCompletedEventHandler intiateNewCompleted;
        
        /// <remarks/>
        public event OtpVerifyCompletedEventHandler OtpVerifyCompleted;
        
        /// <remarks/>
        public event OtpVerifyyuvaCompletedEventHandler OtpVerifyyuvaCompleted;
        
        /// <remarks/>
        public event SendOTPCompletedEventHandler SendOTPCompleted;
        
        /// <remarks/>
        public event SendOTPyuvaCompletedEventHandler SendOTPyuvaCompleted;
        
        /// <remarks/>
        public event YUVSendOTPCompletedEventHandler YUVSendOTPCompleted;
        
        /// <remarks/>
        public event YuvaOtpVerifyCompletedEventHandler YuvaOtpVerifyCompleted;
        
        /// <remarks/>
        public event YUVSendAuthCompletedEventHandler YUVSendAuthCompleted;
        
        /// <remarks/>
        public event YuvaOtpVerifyAuthCompletedEventHandler YuvaOtpVerifyAuthCompleted;
        
        /// <remarks/>
        public event YUVSendOTP174CompletedEventHandler YUVSendOTP174Completed;
        
        /// <remarks/>
        public event YuvaOtpVerify174CompletedEventHandler YuvaOtpVerify174Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/intiate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string intiate(string strOTP, string Aadhaarno) {
            object[] results = this.Invoke("intiate", new object[] {
                        strOTP,
                        Aadhaarno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void intiateAsync(string strOTP, string Aadhaarno) {
            this.intiateAsync(strOTP, Aadhaarno, null);
        }
        
        /// <remarks/>
        public void intiateAsync(string strOTP, string Aadhaarno, object userState) {
            if ((this.intiateOperationCompleted == null)) {
                this.intiateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnintiateOperationCompleted);
            }
            this.InvokeAsync("intiate", new object[] {
                        strOTP,
                        Aadhaarno}, this.intiateOperationCompleted, userState);
        }
        
        private void OnintiateOperationCompleted(object arg) {
            if ((this.intiateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.intiateCompleted(this, new intiateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/intiateold", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string intiateold(string strOTP, string Aadhaarno) {
            object[] results = this.Invoke("intiateold", new object[] {
                        strOTP,
                        Aadhaarno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void intiateoldAsync(string strOTP, string Aadhaarno) {
            this.intiateoldAsync(strOTP, Aadhaarno, null);
        }
        
        /// <remarks/>
        public void intiateoldAsync(string strOTP, string Aadhaarno, object userState) {
            if ((this.intiateoldOperationCompleted == null)) {
                this.intiateoldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnintiateoldOperationCompleted);
            }
            this.InvokeAsync("intiateold", new object[] {
                        strOTP,
                        Aadhaarno}, this.intiateoldOperationCompleted, userState);
        }
        
        private void OnintiateoldOperationCompleted(object arg) {
            if ((this.intiateoldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.intiateoldCompleted(this, new intiateoldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/intiateNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string intiateNew(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            object[] results = this.Invoke("intiateNew", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void intiateNewAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            this.intiateNewAsync(strOTP, Aadhaarno, Agencycode, AgencyName, null);
        }
        
        /// <remarks/>
        public void intiateNewAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName, object userState) {
            if ((this.intiateNewOperationCompleted == null)) {
                this.intiateNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnintiateNewOperationCompleted);
            }
            this.InvokeAsync("intiateNew", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName}, this.intiateNewOperationCompleted, userState);
        }
        
        private void OnintiateNewOperationCompleted(object arg) {
            if ((this.intiateNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.intiateNewCompleted(this, new intiateNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OtpVerify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OtpVerify(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            object[] results = this.Invoke("OtpVerify", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OtpVerifyAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            this.OtpVerifyAsync(strOTP, Aadhaarno, Agencycode, AgencyName, null);
        }
        
        /// <remarks/>
        public void OtpVerifyAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName, object userState) {
            if ((this.OtpVerifyOperationCompleted == null)) {
                this.OtpVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOtpVerifyOperationCompleted);
            }
            this.InvokeAsync("OtpVerify", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName}, this.OtpVerifyOperationCompleted, userState);
        }
        
        private void OnOtpVerifyOperationCompleted(object arg) {
            if ((this.OtpVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OtpVerifyCompleted(this, new OtpVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OtpVerifyyuva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OtpVerifyyuva(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            object[] results = this.Invoke("OtpVerifyyuva", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OtpVerifyyuvaAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            this.OtpVerifyyuvaAsync(strOTP, Aadhaarno, Agencycode, AgencyName, null);
        }
        
        /// <remarks/>
        public void OtpVerifyyuvaAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName, object userState) {
            if ((this.OtpVerifyyuvaOperationCompleted == null)) {
                this.OtpVerifyyuvaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOtpVerifyyuvaOperationCompleted);
            }
            this.InvokeAsync("OtpVerifyyuva", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName}, this.OtpVerifyyuvaOperationCompleted, userState);
        }
        
        private void OnOtpVerifyyuvaOperationCompleted(object arg) {
            if ((this.OtpVerifyyuvaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OtpVerifyyuvaCompleted(this, new OtpVerifyyuvaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOTP(string UIDNUM, string AgencyName, string AgencyCode) {
            object[] results = this.Invoke("SendOTP", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOTPAsync(string UIDNUM, string AgencyName, string AgencyCode) {
            this.SendOTPAsync(UIDNUM, AgencyName, AgencyCode, null);
        }
        
        /// <remarks/>
        public void SendOTPAsync(string UIDNUM, string AgencyName, string AgencyCode, object userState) {
            if ((this.SendOTPOperationCompleted == null)) {
                this.SendOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOTPOperationCompleted);
            }
            this.InvokeAsync("SendOTP", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode}, this.SendOTPOperationCompleted, userState);
        }
        
        private void OnSendOTPOperationCompleted(object arg) {
            if ((this.SendOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOTPCompleted(this, new SendOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOTPyuva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOTPyuva(string UIDNUM, string AgencyName, string AgencyCode) {
            object[] results = this.Invoke("SendOTPyuva", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOTPyuvaAsync(string UIDNUM, string AgencyName, string AgencyCode) {
            this.SendOTPyuvaAsync(UIDNUM, AgencyName, AgencyCode, null);
        }
        
        /// <remarks/>
        public void SendOTPyuvaAsync(string UIDNUM, string AgencyName, string AgencyCode, object userState) {
            if ((this.SendOTPyuvaOperationCompleted == null)) {
                this.SendOTPyuvaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOTPyuvaOperationCompleted);
            }
            this.InvokeAsync("SendOTPyuva", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode}, this.SendOTPyuvaOperationCompleted, userState);
        }
        
        private void OnSendOTPyuvaOperationCompleted(object arg) {
            if ((this.SendOTPyuvaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOTPyuvaCompleted(this, new SendOTPyuvaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YUVSendOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YUVSendOTP(string UIDNUM, string AgencyName, string AgencyCode) {
            object[] results = this.Invoke("YUVSendOTP", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YUVSendOTPAsync(string UIDNUM, string AgencyName, string AgencyCode) {
            this.YUVSendOTPAsync(UIDNUM, AgencyName, AgencyCode, null);
        }
        
        /// <remarks/>
        public void YUVSendOTPAsync(string UIDNUM, string AgencyName, string AgencyCode, object userState) {
            if ((this.YUVSendOTPOperationCompleted == null)) {
                this.YUVSendOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYUVSendOTPOperationCompleted);
            }
            this.InvokeAsync("YUVSendOTP", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode}, this.YUVSendOTPOperationCompleted, userState);
        }
        
        private void OnYUVSendOTPOperationCompleted(object arg) {
            if ((this.YUVSendOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YUVSendOTPCompleted(this, new YUVSendOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YuvaOtpVerify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YuvaOtpVerify(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            object[] results = this.Invoke("YuvaOtpVerify", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YuvaOtpVerifyAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            this.YuvaOtpVerifyAsync(strOTP, Aadhaarno, Agencycode, AgencyName, null);
        }
        
        /// <remarks/>
        public void YuvaOtpVerifyAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName, object userState) {
            if ((this.YuvaOtpVerifyOperationCompleted == null)) {
                this.YuvaOtpVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYuvaOtpVerifyOperationCompleted);
            }
            this.InvokeAsync("YuvaOtpVerify", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName}, this.YuvaOtpVerifyOperationCompleted, userState);
        }
        
        private void OnYuvaOtpVerifyOperationCompleted(object arg) {
            if ((this.YuvaOtpVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YuvaOtpVerifyCompleted(this, new YuvaOtpVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YUVSendAuth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YUVSendAuth(string UIDNUM, string AgencyName, string AgencyCode) {
            object[] results = this.Invoke("YUVSendAuth", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YUVSendAuthAsync(string UIDNUM, string AgencyName, string AgencyCode) {
            this.YUVSendAuthAsync(UIDNUM, AgencyName, AgencyCode, null);
        }
        
        /// <remarks/>
        public void YUVSendAuthAsync(string UIDNUM, string AgencyName, string AgencyCode, object userState) {
            if ((this.YUVSendAuthOperationCompleted == null)) {
                this.YUVSendAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYUVSendAuthOperationCompleted);
            }
            this.InvokeAsync("YUVSendAuth", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode}, this.YUVSendAuthOperationCompleted, userState);
        }
        
        private void OnYUVSendAuthOperationCompleted(object arg) {
            if ((this.YUVSendAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YUVSendAuthCompleted(this, new YUVSendAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YuvaOtpVerifyAuth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YuvaOtpVerifyAuth(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            object[] results = this.Invoke("YuvaOtpVerifyAuth", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YuvaOtpVerifyAuthAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            this.YuvaOtpVerifyAuthAsync(strOTP, Aadhaarno, Agencycode, AgencyName, null);
        }
        
        /// <remarks/>
        public void YuvaOtpVerifyAuthAsync(string strOTP, string Aadhaarno, string Agencycode, string AgencyName, object userState) {
            if ((this.YuvaOtpVerifyAuthOperationCompleted == null)) {
                this.YuvaOtpVerifyAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYuvaOtpVerifyAuthOperationCompleted);
            }
            this.InvokeAsync("YuvaOtpVerifyAuth", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName}, this.YuvaOtpVerifyAuthOperationCompleted, userState);
        }
        
        private void OnYuvaOtpVerifyAuthOperationCompleted(object arg) {
            if ((this.YuvaOtpVerifyAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YuvaOtpVerifyAuthCompleted(this, new YuvaOtpVerifyAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YUVSendOTP174", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YUVSendOTP174(string UIDNUM, string AgencyName, string AgencyCode) {
            object[] results = this.Invoke("YUVSendOTP174", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YUVSendOTP174Async(string UIDNUM, string AgencyName, string AgencyCode) {
            this.YUVSendOTP174Async(UIDNUM, AgencyName, AgencyCode, null);
        }
        
        /// <remarks/>
        public void YUVSendOTP174Async(string UIDNUM, string AgencyName, string AgencyCode, object userState) {
            if ((this.YUVSendOTP174OperationCompleted == null)) {
                this.YUVSendOTP174OperationCompleted = new System.Threading.SendOrPostCallback(this.OnYUVSendOTP174OperationCompleted);
            }
            this.InvokeAsync("YUVSendOTP174", new object[] {
                        UIDNUM,
                        AgencyName,
                        AgencyCode}, this.YUVSendOTP174OperationCompleted, userState);
        }
        
        private void OnYUVSendOTP174OperationCompleted(object arg) {
            if ((this.YUVSendOTP174Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YUVSendOTP174Completed(this, new YUVSendOTP174CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YuvaOtpVerify174", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YuvaOtpVerify174(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            object[] results = this.Invoke("YuvaOtpVerify174", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YuvaOtpVerify174Async(string strOTP, string Aadhaarno, string Agencycode, string AgencyName) {
            this.YuvaOtpVerify174Async(strOTP, Aadhaarno, Agencycode, AgencyName, null);
        }
        
        /// <remarks/>
        public void YuvaOtpVerify174Async(string strOTP, string Aadhaarno, string Agencycode, string AgencyName, object userState) {
            if ((this.YuvaOtpVerify174OperationCompleted == null)) {
                this.YuvaOtpVerify174OperationCompleted = new System.Threading.SendOrPostCallback(this.OnYuvaOtpVerify174OperationCompleted);
            }
            this.InvokeAsync("YuvaOtpVerify174", new object[] {
                        strOTP,
                        Aadhaarno,
                        Agencycode,
                        AgencyName}, this.YuvaOtpVerify174OperationCompleted, userState);
        }
        
        private void OnYuvaOtpVerify174OperationCompleted(object arg) {
            if ((this.YuvaOtpVerify174Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YuvaOtpVerify174Completed(this, new YuvaOtpVerify174CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void intiateCompletedEventHandler(object sender, intiateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class intiateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal intiateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void intiateoldCompletedEventHandler(object sender, intiateoldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class intiateoldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal intiateoldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void intiateNewCompletedEventHandler(object sender, intiateNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class intiateNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal intiateNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void OtpVerifyCompletedEventHandler(object sender, OtpVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OtpVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OtpVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void OtpVerifyyuvaCompletedEventHandler(object sender, OtpVerifyyuvaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OtpVerifyyuvaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OtpVerifyyuvaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendOTPCompletedEventHandler(object sender, SendOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendOTPyuvaCompletedEventHandler(object sender, SendOTPyuvaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOTPyuvaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOTPyuvaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void YUVSendOTPCompletedEventHandler(object sender, YUVSendOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YUVSendOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YUVSendOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void YuvaOtpVerifyCompletedEventHandler(object sender, YuvaOtpVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YuvaOtpVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YuvaOtpVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void YUVSendAuthCompletedEventHandler(object sender, YUVSendAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YUVSendAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YUVSendAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void YuvaOtpVerifyAuthCompletedEventHandler(object sender, YuvaOtpVerifyAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YuvaOtpVerifyAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YuvaOtpVerifyAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void YUVSendOTP174CompletedEventHandler(object sender, YUVSendOTP174CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YUVSendOTP174CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YUVSendOTP174CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void YuvaOtpVerify174CompletedEventHandler(object sender, YuvaOtpVerify174CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YuvaOtpVerify174CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YuvaOtpVerify174CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591